name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pipeline prête
        run: echo "Pipeline configurée, en attente des secrets"